name: "aeso_load_forecasting"
version: "0.1.0"
config-version: 2

profile: "aeso_load_forecasting"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  enable_weather_features: true
  enable_generation_availability_features: true
  enable_intertie_features: true

models:
  aeso_load_forecasting:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
